// Generated by tools/witcher/build-art.mjs from the reviewed art manifest.
export const BESTIARY_ART = {
  '457d92acb05226b4': {
    name: 'Bandit',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/bandit.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/bandit.svg',
  },
  '54339d5f0d4287d6': {
    name: 'Mage',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/mage.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/mage.svg',
  },
  d6b3cbefed0f6802: {
    name: 'Scoia’tael Archer',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/scoia-tael-archer.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/scoia-tael-archer.svg',
  },
  '2e4b9000e7d66051': {
    name: 'Drowner',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/drowner.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/drowner.svg',
  },
  b8b935e20613ee6a: {
    name: 'Ghoul',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/ghoul.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/ghoul.svg',
  },
  '1f83d8de2ab0cabd': {
    name: 'Grave Hag',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/grave-hag.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/grave-hag.svg',
  },
  ae3e33762c444917: {
    name: 'Wraith',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/wraith.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/wraith.svg',
  },
  '4dd850d88e0f4ac9': {
    name: 'Noonwraith',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/noonwraith.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/noonwraith.svg',
  },
  '971a9d2f3e47553a': {
    name: 'Wolf',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/wolf.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/wolf.svg',
  },
  ef40bd8e37e8069c: {
    name: 'Warg',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/wolf.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/warg.svg',
  },
  a96c80647edde546: {
    name: 'Werewolf',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/werewolf.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/werewolf.svg',
  },
  '08494c5667e51fb2': {
    name: 'Siren',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/siren.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/siren.svg',
  },
  '9b81be32baee1f76': {
    name: 'Griffin',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/griffin.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/griffin.svg',
  },
  f95b8db0efd4b514: {
    name: 'Endrega Worker',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/endrega-worker.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/endrega-worker.svg',
  },
  fea9a70aa38ff744: {
    name: 'Endrega Warrior',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/endrega-worker.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/endrega-warrior.svg',
  },
  ec1a7bf1f6650fd6: {
    name: 'Endrega Drone',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/endrega-worker.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/endrega-drone.svg',
  },
  '1f76b4f7cecfc25e': {
    name: 'Arachas',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/arachas.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/arachas.svg',
  },
  '1908fa33754e2485': {
    name: 'Golem',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/golem.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/golem.svg',
  },
  e23cd1e7bd88c8e9: {
    name: 'Fiend',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/fiend.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/fiend.svg',
  },
  '21408f90b2fb2b6c': {
    name: 'Nekker',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/nekker.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/nekker.svg',
  },
  db8dcc264453e1ba: {
    name: 'Nekker Chieftain',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/nekker-chieftain.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/nekker-chieftain.svg',
  },
  '2b275e73224ce345': {
    name: 'Rock Troll',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/rock-troll.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/rock-troll.svg',
  },
  d41ac7dd9f825a77: {
    name: 'Wyvern',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/wyvern.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/wyvern.svg',
  },
  b331be25f86742ff: {
    name: 'Katakan',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/katakan.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/katakan.svg',
  },
  f1233a256e78752d: {
    name: 'Endrega Queen',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/arachas.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/endrega-queen.svg',
  },
  '722f932ec776d939': {
    name: 'Cat',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/cat.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/cat.svg',
  },
  '7565c9f299524893': {
    name: 'Dog',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/dog.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/dog.svg',
  },
  '7ac58149c0a29df1': {
    name: 'Bird',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/bird.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/bird.svg',
  },
  '87e4f177ef97c222': {
    name: 'Serpent',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/serpent.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/serpent.svg',
  },
  '0bbb5417bc60d779': {
    name: 'Horse',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/horse.svg',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/horse.svg',
  },
  feab0b796f74c975: {
    name: 'War Horse',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/war-horse.svg',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/war-horse.svg',
  },
  '01ff85ab29e13613': {
    name: 'Ox',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/ox.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/ox.svg',
  },
  f1b9580dfef0b1dc: {
    name: 'Mule',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/mule.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/mule.svg',
  },
  d6a824457d808ad4: {
    name: '“Crucible” Kowal',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/kowal.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/kowal.svg',
  },
  '67cbff9e3d9340a3': {
    name: 'Lord Nowak',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/nowak.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/nowak.svg',
  },
  '41358d2950c03502': {
    name: 'Woolabag',
    portrait: 'systems/witcher-rilerena/assets/bestiary/portraits/rock-troll.webp',
    token: 'systems/witcher-rilerena/assets/bestiary/tokens/woolabag.svg',
  },
};
