export const SYSTEM_ID = 'witcher-rilerena';
export const CORE_SOURCE = 'The Witcher Core Rulebook v1.35';
export const STATS = ['int', 'ref', 'dex', 'body', 'spd', 'emp', 'cra', 'will', 'luck'];
export const SKILLS = {
  awareness: ['Awareness', 'int'],
  business: ['Business', 'int'],
  deduction: ['Deduction', 'int'],
  education: ['Education', 'int'],
  common: ['Language: Common Speech', 'int', 2],
  elder: ['Language: Elder Speech', 'int', 2],
  dwarven: ['Language: Dwarven', 'int', 2],
  monsterLore: ['Monster Lore', 'int', 2],
  socialEtiquette: ['Social Etiquette', 'int'],
  streetwise: ['Streetwise', 'int'],
  tactics: ['Tactics', 'int', 2],
  teaching: ['Teaching', 'int'],
  wildernessSurvival: ['Wilderness Survival', 'int'],
  brawling: ['Brawling', 'ref'],
  dodge: ['Dodge/Escape', 'ref'],
  melee: ['Melee', 'ref'],
  riding: ['Riding', 'ref'],
  sailing: ['Sailing', 'ref'],
  smallBlades: ['Small Blades', 'ref'],
  staffSpear: ['Staff/Spear', 'ref'],
  swordsmanship: ['Swordsmanship', 'ref'],
  archery: ['Archery', 'dex'],
  athletics: ['Athletics', 'dex'],
  crossbow: ['Crossbow', 'dex'],
  sleightOfHand: ['Sleight of Hand', 'dex'],
  stealth: ['Stealth', 'dex'],
  endurance: ['Endurance', 'body'],
  physique: ['Physique', 'body'],
  charisma: ['Charisma', 'emp'],
  deceit: ['Deceit', 'emp'],
  fineArts: ['Fine Arts', 'emp'],
  gambling: ['Gambling', 'emp'],
  grooming: ['Grooming and Style', 'emp'],
  humanPerception: ['Human Perception', 'emp'],
  leadership: ['Leadership', 'emp'],
  persuasion: ['Persuasion', 'emp'],
  performance: ['Performance', 'emp'],
  seduction: ['Seduction', 'emp'],
  alchemy: ['Alchemy', 'cra', 2],
  crafting: ['Crafting', 'cra', 2],
  disguise: ['Disguise', 'cra'],
  firstAid: ['First Aid', 'cra'],
  forgery: ['Forgery', 'cra'],
  pickLock: ['Pick Lock', 'cra'],
  trapCrafting: ['Trap Crafting', 'cra', 2],
  courage: ['Courage', 'will'],
  hexWeaving: ['Hex Weaving', 'will', 2],
  intimidation: ['Intimidation', 'will'],
  spellCasting: ['Spell Casting', 'will', 2],
  resistMagic: ['Resist Magic', 'will', 2],
  resistCoercion: ['Resist Coercion', 'will'],
  ritualCrafting: ['Ritual Crafting', 'will', 2],
};

const location = (id, label, min, max, aim, multiplier) => ({
  id,
  label,
  min,
  max,
  aim,
  multiplier,
  sp: 0,
  maxSp: 0,
});
export const HUMANOID_LOCATIONS = [
  location('head', 'Head', 1, 1, -6, 3),
  location('torso', 'Torso', 2, 4, -1, 1),
  location('rightArm', 'Right arm', 5, 5, -3, 0.5),
  location('leftArm', 'Left arm', 6, 6, -3, 0.5),
  location('rightLeg', 'Right leg', 7, 8, -2, 0.5),
  location('leftLeg', 'Left leg', 9, 10, -2, 0.5),
];
export const MONSTER_LOCATIONS = [
  location('head', 'Head', 1, 1, -6, 3),
  location('torso', 'Torso', 2, 5, -1, 1),
  location('rightLimb', 'Right limb', 6, 7, -3, 0.5),
  location('leftLimb', 'Left limb', 8, 9, -3, 0.5),
  location('tailWing', 'Tail / wing', 10, 10, -2, 0.5),
];
export const DAMAGE_TYPES = ['slashing', 'piercing', 'bludgeoning', 'elemental', 'fire', 'poison'];
export const COVER = {
  'Stone wall': 30,
  'Large tree': 30,
  'Brick wall': 25,
  'Wooden wall': 10,
  'Heavy wooden door': 15,
  'Steel door': 20,
  Cart: 10,
  Tent: 5,
  'Thatch roof': 7,
  'Wooden barrel': 10,
  Brambles: 7,
};
export const CONDITIONS = {
  prone: 'Prone',
  staggered: 'Staggered',
  stunned: 'Stunned',
  unconscious: 'Unconscious',
  dead: 'Dead',
  fire: 'On fire',
  poison: 'Poisoned',
  bleeding: 'Bleeding',
  frozen: 'Frozen',
  intoxicated: 'Intoxicated',
  hallucinating: 'Hallucinating',
  nausea: 'Nausea',
  suffocating: 'Suffocating',
  blinded: 'Blinded',
  grappled: 'Grappled',
  pinned: 'Pinned',
  activelyDodging: 'Actively dodging',
};
export const ITEM_TYPES = [
  'weapon',
  'armor',
  'shield',
  'gear',
  'alchemical',
  'component',
  'diagram',
  'skill',
  'profession',
  'wound',
  'mount',
  'enhancement',
  'ability',
];
export const SPECIAL_ACTIONS = [
  'normal',
  'punch',
  'kick',
  'pushKick',
  'charge',
  'pommel',
  'disarm',
  'takeWeapon',
  'trip',
  'grapple',
  'pin',
  'choke',
  'throw',
  'escape',
  'feint',
  'joint',
];
