/** Deterministic vector token framing around unchanged, embedded book/generated art. */
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { format, resolveConfig } from 'prettier';

const root = path.resolve(import.meta.dirname, '../..');
const prefix = 'systems/witcher-rilerena/';
const art = JSON.parse(await fs.readFile(path.join(root, 'data/witcher/bestiary-art.json'), 'utf8'));
const actorsPath = path.join(root, 'data/witcher/bestiary.json');
const actors = JSON.parse(await fs.readFile(actorsPath, 'utf8'));
const catalog = {};
const escape = (value) =>
  String(value).replace(
    /[&<>"']/g,
    (c) =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&apos;',
      })[c]
  );
assert.equal(art.actors.length, actors.length, 'Every bestiary Actor needs an art entry');
for (const entry of art.actors) {
  const actor = actors.find((a) => a._id === entry.id);
  assert(actor && actor.name === entry.name, `Unknown art Actor: ${entry.name}`);
  assert(!catalog[entry.id], `Duplicate art entry: ${entry.name}`);
  for (const file of [entry.portrait, entry.token, entry.image ?? entry.portrait])
    assert(
      /^assets\/bestiary\/(?:portraits|tokens|illustrations)\/[a-z0-9-]+\.(?:webp|png|jpg|svg)$/.test(file),
      file
    );
  const [x, y, size] = entry.viewport;
  assert([x, y, size, entry.width, entry.height].every(Number.isFinite));
  assert(
    size > 0 && x >= 0 && y >= 0 && x + size <= entry.width && y + size <= entry.height,
    `Token crop outside portrait: ${entry.name}`
  );
  const image = entry.image ?? entry.portrait;
  const bytes = await fs.readFile(path.join(root, image));
  const mime = image.endsWith('.jpg') ? 'jpeg' : path.extname(image).slice(1);
  const dataUrl = `data:image/${mime};base64,${bytes.toString('base64')}`;
  if (entry.portraitViewport) {
    const [px, py, pw, ph] = entry.portraitViewport;
    assert([px, py, pw, ph].every(Number.isFinite));
    assert(px >= 0 && py >= 0 && pw > 0 && ph > 0 && px + pw <= entry.width && py + ph <= entry.height);
    assert(entry.portrait.endsWith('.svg'));
    await fs.mkdir(path.dirname(path.join(root, entry.portrait)), { recursive: true });
    await fs.writeFile(
      path.join(root, entry.portrait),
      `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${pw}" height="${ph}" viewBox="${px} ${py} ${pw} ${ph}" role="img" aria-label="${escape(entry.name)}"><image width="${entry.width}" height="${entry.height}" xlink:href="${dataUrl}"/></svg>\n`
    );
  }
  const scale = 512 / size;
  const number = (v) => Number(v.toFixed(4));
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512" height="512" viewBox="0 0 512 512" role="img" aria-label="${escape(entry.name)}">
<defs><clipPath id="portrait"><circle cx="256" cy="256" r="243"/></clipPath></defs>
<circle cx="256" cy="256" r="253" fill="#211e19"/>
<image x="${number(-x * scale)}" y="${number(-y * scale)}" width="${number(entry.width * scale)}" height="${number(entry.height * scale)}" clip-path="url(#portrait)" xlink:href="${dataUrl}"/>
<circle cx="256" cy="256" r="246" fill="none" stroke="#b69a68" stroke-width="5"/>
<circle cx="256" cy="256" r="252" fill="none" stroke="#6c5940" stroke-width="2"/>
</svg>
`;
  await fs.mkdir(path.dirname(path.join(root, entry.token)), { recursive: true });
  await fs.writeFile(path.join(root, entry.token), svg);
  const record = { name: entry.name, portrait: prefix + entry.portrait, token: prefix + entry.token };
  catalog[entry.id] = record;
  actor.img = record.portrait;
  actor.prototypeToken.texture.src = record.token;
  actor.flags['witcher-rilerena'].bestiaryId = entry.id;
}
await fs.writeFile(actorsPath, JSON.stringify(actors, null, 2) + '\n');
const catalogPath = path.join(root, 'module/witcher/bestiary-art.js');
await fs.writeFile(
  catalogPath,
  await format(
    '// Generated by tools/witcher/build-art.mjs from the reviewed art manifest.\n' +
      `export const BESTIARY_ART = ${JSON.stringify(catalog, null, 2)};\n`,
    { ...(await resolveConfig(catalogPath)), parser: 'babel' }
  )
);
console.log(
  `Assigned portraits and self-contained round tokens to ${Object.keys(catalog).length} bestiary Actors.`
);
